### ISSUE TITLE
Site breaks when nothing is typed into the search bar 

### ISSUE THREAD

**Issue by ijiang** [calebROlson/idb#100]
Currently, if a user were to click on the submit button without having typed into the search field, the site will break. 
Possible solution: Disable the submit button until a character is entered.

**Comment by calebROlson** [comment]
It 404s. Is this intended? It seems to make some sense, but maybe we shouldn't allow a user to click submit if the search box is empty? I don't know.

**Comment by ijiang** [comment]
Oh, my bad. I forgot to mark this issue as resolved. 
I think disabling the search button until something is typed makes sense though. Perhaps for the final phase, that'll be a feature.

**Comment by ijiang** [comment]
The search box is disabled if a user attempts to click search while the search box is empty or if the search term is just whitespace characters. I'm going to wait a bit to mark this as resolved in case there's a bug.

**Comment by calebROlson** [comment]
Seems to work for me!
