### ISSUE TITLE
As a user, I want to be able to order multiple attributes of a model alphabetically

### ISSUE THREAD

**Issue by zynect** [calebROlson/idb#101]

**Comment by calebROlson** [comment]
Right now the backend has this functionality, and it took about 3 hours. Doing multiple orderings is the same as doing one, so it was not much trouble.

The front end is also able to do this for webcams; it just needs to be added to cities and flights.

I think it might take another hour or 2, so in total about 5 hours.

**Comment by zynect** [comment]
In total, this issue took about 6 hours for both the front end and the back end to complete their tasks.
