### ISSUE TITLE
Refactor instance pages

### ISSUE THREAD

**Issue by zibbycakes** [calebROlson/idb#104]
- [x] update external links to look like links
- [x] update presentation of lists (maybe an expandable panel, as those look nicer on any sized page?)
- [x] titles for media

If I think of more things, I'll add them to this checklist and comment that I updated.

**Comment by zibbycakes** [comment]
Update: removed media on instance pages because airline logo is too hard

**Comment by calebROlson** [comment]
The lists are now expandable by @ijiang in 7af3863bba9ac4b8194512677d1b460d512ed839

**Comment by zibbycakes** [comment]
We decided not to refacto the timezone. Removed.

**Comment by zibbycakes** [comment]
Finished
