### ISSUE TITLE
User should have the navbar options available in the top right corner to the left of the search bar as opposed to shifted left

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#107]

**Comment by zibbycakes** [comment]
Is this something we actually want to do? I think that style-wise the way we have it now makes the most sense.

**Comment by yvonneKim** [comment]
This is bullshit. 

*Judge Judy gavel slam* dismissed.

**Comment by zibbycakes** [comment]
we have to negotiate this

**Comment by calebROlson** [comment]
@dtalamas @Daniel9650 Could you please clarify the issue? Would you like it to be more similar to the navbar on your website at http://poptopic.org/?

**Comment by calebROlson** [comment]
We were told that it is fine the way it is now.
