### ISSUE TITLE
User should not have the view of the grid obstructed by the filter panel

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#108]

**Comment by zibbycakes** [comment]
This will be fixed when the filter panel is moved to the top of the page instead of to the side. Might take 2 hours.

**Comment by calebROlson** [comment]
This has been done by 730ba0387905501d7867f89499d3586463d4b52d

**Comment by zibbycakes** [comment]
This was helped by moving the filter panel to the top instead of having it to the left. It took about 2 hours to do that.
