### ISSUE TITLE
User should still have similar experience to normal when site is scaled smaller or thinner.

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#109]
The about page, and model page grid scale poorly

**Comment by zibbycakes** [comment]
I'm not really sure how to do this, so it might take longer than expected. I'm thinking it'll take around 5 hours or so.

**Comment by calebROlson** [comment]
Fixed by @zibbycakes in 0d3a772d1fec0dc5e405d3de91e81640ad264319. 
It took about 4 or 5 hours.
