### ISSUE TITLE
User should have better way to select 'True' and 'False' for the Live field in the filtering sidebar, such as a switch or checkbox, as opposed to type selection bar.

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#112]

**Comment by zibbycakes** [comment]
I noticed an issue with the checkbox where its default value is being set to true sometimes

**Comment by calebROlson** [comment]
A related problem is that when you click the check box, click submit it works-- then click submit again and it sets live=%5Bobject+Object%5D

**Comment by calebROlson** [comment]
The checkbox is set to true automatically when any other filter is selected.
