### ISSUE TITLE
City names not appearing in search results

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#119]
Example:
AR7818 is a Aerolineas Argentinas flight from , to , . 
Livno is a webcam tagged City in , Bosnia and Herzegovina

**Comment by ijiang** [comment]
I believe this occurs because api.projectrunway.me doesn't return the names of the cities and regions, while api.dev.projectrunway.me does, and for the 3rd phase's submission the server was switched to the former.

**Comment by calebROlson** [comment]
Yeah you're right. I will look into it tomorrow or this weekend.

**Comment by calebROlson** [comment]
This works now.
