### ISSUE TITLE
Pagination for search results going past max results

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#120]
Example:
http://projectrunway.me/SearchResult/page/119?q=+austin

This should either have results or not have an option to visit this page.

**Comment by ijiang** [comment]
Good catch there. I believe it's currently not redirecting to a 404 not found page because the corresponding API call doesn't return a 404. I think this is something for the back-end? Estimating it'll take 1-2 hours to do.

**Comment by ijiang** [comment]
I figured out a simple way around this issue that doesn't rely on the API returning a 404 since the dev.api site hasn't been updated yet.

**Comment by calebROlson** [comment]
Fixed by @ijiang in e318eec50fdfa9bc4766f980a448cb886ae0104d
