### ISSUE TITLE
Display different messages during search vs no results found

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#121]
Right now we have it say 

> You searched for example, but it matched nothing in our database...yet. Please wait a few seconds for our data to load. If a few seconds have passed and you're still reading this... Then there actually is no result for your query.

But it probably should have a small graphic that indicates it is loading, then after no results are found, should have a separate message indicating such.

**Comment by ijiang** [comment]
This is a good point. I forgot we had used a loading bar for pretty much every other model. This should take an hour at most.

**Comment by calebROlson** [comment]
This works as intended now-- if no results are found, that is displayed. There is also a loading bar during search.
