### ISSUE TITLE
Remove deprecated code and associated tests from backend

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#126]
Right now we have remnants of old code from the 2nd phase. They are simply calling the more generalized versions of themselves right now and are only used for tests, so it would make sense to remove them and their associated tests, or rather rewrite the tests to use the more generalized version and remove the deprecated code.

**Comment by yvonneKim** [comment]
Backend tests? I didn't do those. My frontend tests are all kept cutting edge and clean.
