### ISSUE TITLE
First character of search is removed on certain occasions

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#127]
Click into the search bar and search. It works like normal.
Now click into the search bar and backspace once, then search "e". It 404s as if there is nothing in there.
Now click into the search bar and backspace once, then search "houston". It searches for "ouston".

By default, there is a space inserted into the search bar. If you remove it, it doesn't take the first character.

**Comment by yvonneKim** [comment]
Resolve this? It's fixed now on the latest dev build.
