### ISSUE TITLE
Every instance of model has it's own page- should change to dynamically making it display within it's respective model page

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#20]
For example, each of our cities is accessed via route <website url>/cities/1, 2, 3 etc.

Since the number of items we have to show is large, we must replace this solution with one that dynamically displays the info page for each model item *within* the screen for the model. Maybe a popup, iframe, using setState() or something? Inspiration: those shitty pop-up ads that remind you to turn off ad-block on news sites.

**Comment by calebROlson** [comment]
This has been completed.
