### ISSUE TITLE
As a developer, I want to access information available on the site via a RESTful API

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#24]
Eventually!

**Comment by calebROlson** [comment]
This has already taken many hours. About 20. 

This is a large user story. Maybe we should break it into pieces. Maybe each API endpoint could be a story, since the features are sort of separate.

**Comment by calebROlson** [comment]
The API endpoints are finished, we are just waiting on getting more data in the database. It took about another 10-15 hours, so about 30-40 hours total because of some issues we were having.
