### ISSUE TITLE
Authenticating github api requests

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#31]
Unauthenticated, github only allows 60 requests per hour per ip. If we authenticate via basic, personal key, or OAuth, it raises the limit to 5,000 per hour per the user registered under.

Best way to do this, I think, would be for Caleb, our webmaster, to get a personal key token and then store it in our production server environment. Then, the code can extract it as an environment variable. This is the only way to safely authenticate without hardcoding a password or token right in the code.

**Comment by calebROlson** [comment]
Yes, I made a key but I don't know if we ever figured out how to use it-- if I send you the key will you be able to do it?

**Comment by yvonneKim** [comment]
I can give it a go tonight, but idk if I can do it in time for the deadline? As long as we don't all visit the "About" page over and over, we should leave a few requests open for when Downing opens the page to view, since only the "About" page is the one that makes any api requests.

**Comment by calebROlson** [comment]
Should we do this by calling the Flask API now?

**Comment by yvonneKim** [comment]
Yes, I think we have "solved" this problem now. We could just have that data in our internal db and call the api for /about. 

Will close and re-open as a new issue.
