### ISSUE TITLE
Display real bios for each teammate.

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#33]
I think it would be better to have real information.

**Comment by calebROlson** [comment]
Caleb is a computer science major with a business minor who expects to graduate in Spring 2019. <interesting fact>. Has visited England and flown to Florida, Nevada, and Illinois. He prefers working on the database, back-end, but is willing to do whatever is necessary to help his team.

**Comment by yvonneKim** [comment]
She's itching to graduate in Spring 2018 with a B.S.A. in Computer Science, minor in Sociology. Has only been to Mexico and South Korea but plans on expanding that list. Just loves the feeling of typing fast and solving problems.

**Comment by zibbycakes** [comment]
Allyson is Computer Science major graduating in Spring 2018. She excels at front-end programming, but likes to learn new technologies. She's only been to Mexico, but hopes to expand that list one day!

**Comment by zynect** [comment]
He is a computer science major with a business certificate who has spent almost 3 years at UT Austin. He has visited China and Canada, as well as a few states within the US. He likes to work on the back-end, and does whatever is needed by the team, which includes writing up reports and documentation.

**Comment by ijiang** [comment]
Irene is double majoring in Computer Science and Asian American Studies with a minor in Sociology and is graduating in Spring 2018. Irene has been to China, Japan, and New Zealand with an upcoming trip to Taiwan during spring break. Prefers to work front-end, but is content with any task. Can't make a fist with her hands... does that have any correlation with how slow she types?
