### ISSUE TITLE
Constraining url routing to only go to legitimate pages

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#45]
For example, projectrunway.me/nothing/nothing leads to a blank placeholder page generated by React. I think this is caused by either client-side (React) or server-side (Flask) catch-all routing. Obviously, this isn't right.

**Comment by zibbycakes** [comment]
As per a conversation with Caleb:
```
// all our routes are above
//some more routes
<Route path='*' exact={true} component={My404Component} />
```

then we make a 404 component.

**Comment by zibbycakes** [comment]
Made some progress with this in commit https://github.com/calebROlson/idb/commit/7e8e5866cccc48b09f62d6d392c8c81b0d342e7f. However, we need to validate ids for flight/city/webcam pages and their grids. When not valid, it should show the 404 page

**Comment by calebROlson** [comment]
@ijiang took care of this in this commit 51695c4, so it works now as far as I can tell.
