### ISSUE TITLE
As a user, I want to view diverse and numerous sets of data in a grid layout.

### ISSUE THREAD

**Issue by ijiang** [calebROlson/idb#49]
Estimated Completion Time: 15 hours.

Will need to be able to display results and have the database + API side successfully working. The front-end will have a neat concise grid template done.

**Comment by ijiang** [comment]
Estimated completion time: 5 hrs.

**Comment by calebROlson** [comment]
I think this might be too vague. It should address some specific feature. Is this about the grid view?

**Comment by zibbycakes** [comment]
I was thinking the same thing. These should be as specific as possible.

**Comment by ijiang** [comment]
It was to address this phase's requirement of having many instances of each model, but I'll make it more specific.

**Comment by ijiang** [comment]
Finished in ~12 hours.
