### ISSUE TITLE
As a user, I want to view at least 10 flights on the flights page

### ISSUE THREAD

**Issue by yvonneKim** [calebROlson/idb#50]
EST TIME TO COMPLETION: 20 HRS

**Comment by calebROlson** [comment]
Are we supposed to sort in this phase? I thought that was next phase. Maybe we could limit this in scope to simply I want to view prices of X number of flights?

**Comment by calebROlson** [comment]
We can do this now right?

**Comment by ijiang** [comment]
Yes! The grid of flights now reflects all flights we have & it look ~4 hours (if we exclude the amount of time to populate the database).
