### ISSUE TITLE
As a user, I want to be able to be able to see what a city currently looks like.

### ISSUE THREAD

**Issue by zibbycakes** [calebROlson/idb#53]
Specifically, there should be multiple views (webcams) of the same city that can be easily accessed through the page for that city.

EST Time: 10 hrs

**Comment by calebROlson** [comment]
How are we going to display multiple views? I thought a carousel of their thumbnails could be nicely displayed on each city's page.

**Comment by zibbycakes** [comment]
To achieve this, the API would have to return a list of webcams that are related to cities.

**Comment by zibbycakes** [comment]
The simplest way to show multiple views, at least at first, would be to have a list of links or buttons. We might have to limit the number of webcams that show up on a city page though, because it might become too crowded when we have a lot of data.

**Comment by calebROlson** [comment]
Related to #79 . Was fixed by @ijiang .

Currently we have links between a city and its webcams. They are simply links right now but I think that is enough to close this issue. If we want to make them images, a new issue can be opened.

**Comment by zynect** [comment]
This issue took about 15 hours to complete, the extra time being used to implement a function that acquires all webcams located near a city.
