### ISSUE TITLE
Flight API endpoint should return Destination and Source airports

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#59]
Currently we are returning the cities for these pieces of information.

We should be returning the airports themselves, then if we need the city we can grab that info from the airport code.

**Comment by zibbycakes** [comment]
can we actually grab city info from aiport codes? I was thinking we still had sourceCity and destinationCity, as well as a sourceAirport and destinationAirport. I guess design choice is up to you guys, as long as frontend can still access those 4 piece of information.
