### ISSUE TITLE
As a traveler, I want to see all flights from my city to a destination city

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#62]
There's only three cities and three flights right now. We should add many flights from many cities so a user could actually see flights from their own city. Unless they live in Copenhagen they won't be satisfied.

This will take the completion of our database population with real data as well as the front end being expanded to allow more than two flights per city. 

Once the backend portion is in place it will probably take about five hours to put multiple flights per city.

**Comment by calebROlson** [comment]
We have not gotten flights totally hammered down yet.

@zynect has spent some time working on it.
I've spent time trying to get a general basis for us to work on.
That has taken about 10 hours.

The time to complete the story may be another 5-6 hours. I estimate the whole thing will take about 15 hours.

**Comment by zibbycakes** [comment]
Frontend has a basic template for flights right now on the `dynamic-gen` branch. Since the backend hasn't been completely figured out yet, I will help to update the template once the models are in place.

**Comment by zynect** [comment]
In total, this issue took 25 hours to complete. The time was much greater than our estimate since there were many API and database problems that we didn't anticipate when acquiring flight data and matching it to cities.
