### ISSUE TITLE
Create a way for the cities API to return a set of cities at once

### ISSUE THREAD

**Issue by zibbycakes** [calebROlson/idb#65]
This is necessary to make translating city ids (which is given in the webcam fetch) into city/region names. The alternative is to fetch all of the cities then look through the ones needed on the front end OR calling fetch <number of items on the grid page> times for each city name. I feel like these are not good ways to approach this.

This could maybe be done by adding `?id=1,5,6,7`, to fetch the cities that have ids 1, 5, 6, and 7

**Comment by zibbycakes** [comment]
Until we figure out a way to deal with this, I'm gonna hold off on displaying the city name on the webcam grid.

**Comment by calebROlson** [comment]
Will do. But... Would it be better to just return the city name as part of the webcam API call?

**Comment by zibbycakes** [comment]
That could also be a solution. The ID would still be needed for linking purposes though.

I figured the initial approach I suggested would be more database-like. It would be like a `join` between Webcams and Cities on city_id, right?

**Comment by calebROlson** [comment]
Done by aaa9aa3

Syntax is /cities?id=a&id=b...&id=z
