### ISSUE TITLE
Dynamic generation breaks when you use back/forward arrows on the browser

### ISSUE THREAD

**Issue by zibbycakes** [calebROlson/idb#69]
Need to figure out a way to refresh the page with given data based on the url (ie, page number for the grid or webcam number for an individual template) when the back/forward arrows are used.

**Comment by calebROlson** [comment]
Maybe this is related to #45? It might be a routing issue or something.

**Comment by yvonneKim** [comment]
Exact same problem here? https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually

**Comment by zibbycakes** [comment]
Actually, I'm not sure if there's a problem after all... Let me know if you guys ever get this problem again, because I can't seem to recreate the issues I was having.

**Comment by calebROlson** [comment]
Fixed? Works for me too now.
