### ISSUE TITLE
Reconcile differences between external APIs and our City model

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#70]
Ray mentioned that the information from the 2 external APIs related to city information are hard to "sync" in a sense.

One provides data by one means, and another provides different data by another. However, there lacks a way to get the same "instance" or city from both since their IDs are obviously different.

There may be a way to figure out which instance we are talking about given some specific data. We will investigate and hopefully figure it out.

This is important since it is necessary to get at least _some_ information about cities before the deadline.

Ray mentions this here 8a45aad86525e3f7b165795ea6cb0677ed7a92a2

**Comment by yvonneKim** [comment]
Solution 1: Use only one of those apis 
Solution 2: Use the actual name of the city as the common identifier to query both apis. Unfortunately, it looks like we have to bug our boy Leo about the broken search function on the aviationedge api  :(

**Comment by calebROlson** [comment]
I think the solution we came up with was to use the IATA codes of cities. 

Translate a city name to its code then lookup the city with that.

**Comment by calebROlson** [comment]
We decided to use a webcam's latitude and longitude to query Google Maps API and get the city and state it is considered to be in.

Then we take those coordinates and use Aviation Edge to find nearby airports and grab flights to and from that airport.

This appears to work.
