### ISSUE TITLE
As a user, I want to be able to filter cities by region or country

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#86]
If I am only interested in viewing a specific set of cities as a user, I should be able to filter those cities by region (like state) or country.

This requires the API respond to this sort of query to only return the cities specified by the front end.

Estimated time to completion: 6-7 hours.

The back end does not need to do very much for this because the existing API already uses SQLAlchemy queries to get information. All that is needed is some convention from the front end to the back end to specify how to structure these queries.

The front end requires more thought, since it needs to know ahead of time which things one can filter by as well as what the value of those things can be. This requires a little extra information from the back end as well as good design on the front end.

**Comment by calebROlson** [comment]
As an update, the backend currently supplies a list of all attributes that can be sorted and filtered on a given model.

That took about 20 minutes to add onto the existing code we had for filtering and sorting.

That takes care of the last paragraph of the above post, meaning that all that is left is using the information provided about what's filterable in the front end to create the query and allow the user to dictate what to filter by.

Then it should take about 3-4 more hours, for a total of about 5 hours. Adding this functionality to the backend was not difficult.

**Comment by zynect** [comment]
The resulting total time spent on this issue was 4 hours.
