### ISSUE TITLE
As a user, I would like to be able to search the website for a term and see all relevant results

### ISSUE THREAD

**Issue by calebROlson** [calebROlson/idb#88]
With the current website, we have thousands of instances of each model type.

This can be overwhelming for a user who only wants to know about a small subset of information or related information without having to filter by a specific attribute.

Therefore it would be nice to add a search function to the website which can return results with words similar to the query inserted by the user.

It would be best to search the whole website; perhaps we could put a search bar in the nav bar.

This requires effort from both the back end and the front end.
The back end must be extended to be able to allow search from the API/front end. This requires either additional modules or using Postgresql's search.

I have begun experimenting with the Python module [Whoosh](http://whoosh.readthedocs.io/en/latest/intro.html) which would make searching simple once an index is built on each instance of each model.

The front end must insert a search bar in the nav bar and decide how to format the results provided by the API.

All of this functionality is not yet implemented in either portions of the website, so time and research is needed to get it implemented properly.

**Estimated time to completion**: ~5-6 hours for the back end, ~2-3 hours for the front end, so about 10 hours total.

**Comment by calebROlson** [comment]
Another module that I have discovered is a Flask extension called [Flask-Whooshee](http://flask-whooshee.readthedocs.io/en/latest/)


This module works very nicely. After some experimentation, implementing search in the back end will likely only be a couple hours of work.

What Flask-Whooshee does is takes the hassle out of using Whoosh. It integrates with Flask-SQLAlchemy by using annotations which register a model as a Whoosh "document" type. Then, when a row is added to the database, it takes the information and indexes it into the Whoosh index using a given schema specified by us. This greatly limits the amount of support code we will need to write to use Whoosh, while giving us all the speed/features of Whoosh including relevance sorting, etc.

Perhaps the time to complete the back end has been shortened to about 3-4 hours. The main issue is figuring out how to format queries from the front end into a proper search as well as figuring out how to mix the results from each model type as Flask-Whooshee natively supports individual models but requires a custom implementation of a searcher if combining multiple models.

One idea is search each model independently and merge the results.

**Comment by calebROlson** [comment]
As an update, this has been implemented in the backend for a day or two.

We also have a search bar on the front end in the nav bar. All that is left to do is send the request to the API and receive results and make them pretty on the results page. This only took about 2 hours to get working in the backend.

The front end likely needs another 2 or 3 hours, for a total of 5-6 hours.

**Comment by ijiang** [comment]
As stated by Ray, the total time was 10 hours. Improvements made to the front end were displaying search results in a readable fashion (ex: A webcam is located in x city with coordinates in y, z). The results were also limited to certain number per model.
