### ISSUE TITLE
As a user, I want to be able to filter and sort at the same time.

### ISSUE THREAD

**Issue by zibbycakes** [calebROlson/idb#96]
This would allow for being able to find things in a way that is most natural to me (the user).

**Comment by calebROlson** [comment]
The backend has the functionality for this. It took about 3-4 hours.

I think the front end is still working on this for models besides webcams.

I think it might take another 2-3, so maybe 7-8 hours total.

**Comment by zibbycakes** [comment]
Filtering took at least 8 hours on its own for front-end, but afterwards filtering by more than one item took maybe an hour more. 9 total
