### ISSUE TITLE
URL contains an "?undefined" part when a filter/order hasn't been applied and the page number is changed.

### ISSUE THREAD

**Issue by zibbycakes** [calebROlson/idb#99]
I've handled this so that it doesn't actually affect anything (I hope), but it still looks unsightly and I'm not sure how to prevent it from appearing.

**Comment by calebROlson** [comment]
Fixed by badbafd9df3dde742ceac94d09010397d4758e4d

Pagination was expecting a query, but wasn't receiving one. Now we check if we get one and append it if so, else append nothing to the link.
